config/routes.rb
Rails.application.routes.draw do

  get 'landings/index'

  get 'landings/get_leads'
  
  post 'landings/receive'

  root 'landings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery prepend: true # Soluciona el error ActionController::InvalidAuthenticityToken
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end

  def receive
    #User.create(email: params[:email])
    @user = User.new(email: params[:email])
    if @user.save
      redirect_to root_path,
        notice: "Te has registrado"
    else
      redirect_to root_path,
      alert: "No se completo el registro, intalo de nuevo"
    end
  end

  def get_leads
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/get_leads.html.erb
<h1>E-mails</h1>

<ul>
  <% @users.each do |u| %>
    <li><%= u.email %></li>
  <% end %>
</ul>

app/views/landings/index.html.erb
<h1>Este es el primer formulario del libro</h1>
<%= flash[:notice] %>
<%= flash[:alert] %>
<form method="POST" action="<%= landings_receive_path %>" class="form">
  <label for="email">E-mail</label>
  <input name="email">
  <input type="submit" value="Suscribirse">
</form>

<%= form_tag landings_receive_path, method: :post, class: 'form' %>
  <%= label_tag "email", "Email" %>
  <%= email_field_tag "email" %>
<%= submit_tag "Suscribirse", class: "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondForm</title>

    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>